###
Template for the browser initialization script generated by the optimizer.
CAPS-named variables are placeholders and should be replaced with the actual values computed by the optimzer.
###

require.config(COMPUTED_REQUIREJS_CONFIG)

jsGroupMap = JS_GROUP_MAP
cssGroupMap = CSS_GROUP_MAP

groupLoadingMap = {}
for groupId, modules of jsGroupMap
  groupFile = "/assets/z/#{groupId}.js"
  for module in modules
    groupLoadingMap[module] = groupFile

require.config(groupLoadingMap: groupLoadingMap)

require ['cord!init/browserInit', 'cord!css/browserManager'], (browserInit, cssManager) ->
  cssManager.setGroupLoadingMap(cssGroupMap)
  browserInit()
