###
Template for the browser initialization script generated by the optimizer.
Some CAPS-named variables are placeholders and should be replaced with the actual values computed by the optimizer.
###

baseUrl = if global.config.localFsMode then '' else '/'

require.config(COMPUTED_REQUIREJS_CONFIG)
require.config(baseUrl: baseUrl)

window.CORD_IS_BROWSER = true
window.CORD_PROFILER_ENABLED = global.config.debug.profiler.enable

jsGroupMap = JS_GROUP_MAP
cssGroupMap = CSS_GROUP_MAP

groupLoadingMap = {}
for groupId, modules of jsGroupMap
  groupFile = "#{baseUrl}assets/z/#{groupId}.js"
  for module in modules
    groupLoadingMap[module] = groupFile

require.config(groupLoadingMap: groupLoadingMap)

require [
  'cord!init/browserInit',
  'cord!css/browserManager'
  if CORD_PROFILER_ENABLED then 'cord!init/profilerInit' else undefined
], (browserInit, cssManager, profilerInit) ->
  profilerInit() if CORD_PROFILER_ENABLED
  cssManager.setGroupLoadingMap(cssGroupMap)
  browserInit.init()
